name: Dependency Review

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.gradle'
      - '**/*.gradle.kts'
      - '**/gradle-wrapper.properties'
      - '**/gradle.properties'
      - '**/lib.versions.toml'
  pull_request_target:
    branches: [ "main" ]
    paths:
      - '**/*.gradle'
      - '**/*.gradle.kts'
      - '**/gradle-wrapper.properties'
      - '**/gradle.properties'
      - '**/lib.versions.toml'

# Limit concurrent runs for pull requests to save resources
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    name: Review Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: read  # Required for PR scanning

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: critical  # Fail workflow on critical vulnerabilities
          deny-licenses: LGPL-2.0, AGPL-3.0  # Optional: Fail on specific licenses