name: Dependency Submission

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.gradle'
      - '**/*.gradle.kts'
      - '**/gradle-wrapper.properties'
      - '**/gradle.properties'
      - '**/lib.versions.toml'
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggers

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  submit-dependencies:
    name: Submit Dependency Graph
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      actions: read   # Needed for workflow caching
      security-events: write  # Needed for dependency graph submission

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone is sufficient for dependency scanning

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        continue-on-error: true  # Prevent workflow failure if submission fails
