name: Engine-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: "Checkout Sources"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create reports directory
        run: |
          mkdir -p build/reports
      - name: Setup Opengl
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-utils libgl1 libglx-mesa0 xvfb x11-utils
      - name: "Setup environment variables"
        run: |
          echo "LIBGL_ALWAYS_SOFTWARE=1" >> $GITHUB_ENV
          echo "MESA_LOADER_DRIVER_OVERRIDE=softpipe" >> $GITHUB_ENV
      - name: Start xvfb
        run: |
          sudo Xvfb :99 -ac -screen 0 1024x768x24 > build/reports/xvfb.log 2>&1 &
          export DISPLAY=:99
          echo "DISPLAY=:99" >> $GITHUB_ENV
          sleep 3  # Give xvfb some time to start
      - name: Verify Mesa3D Installation
        run: |
          glxinfo | grep "OpenGL"
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'oracle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build with Gradle Wrapper
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
      # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
